import { College, Subject, ExamType, QuestionPaper, PaperReport } from './types';

export const INITIAL_COLLEGE: College = {
  id: 'col-gmc-01',
  name: 'Government Medical College (GMC)',
  code: 'GMC-MAIN',
  description: 'Primary public medical institution for undergraduate and postgraduate medical education.',
  is_active: true,
  created_at: new Date('2025-01-01').toISOString(),
  updated_at: new Date('2025-01-01').toISOString(),
};

export const INITIAL_SUBJECTS: Subject[] = [
  {
    id: 'sub-anat-01',
    college_id: 'col-gmc-01',
    name: 'Anatomy',
    slug: 'anatomy',
    description: 'Human gross anatomy, histology, embryology, and neuroanatomy.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-phys-02',
    college_id: 'col-gmc-01',
    name: 'Physiology',
    slug: 'physiology',
    description: 'Organ systems, cellular physiological processes, and nerve-muscle mechanisms.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-bioc-03',
    college_id: 'col-gmc-01',
    name: 'Biochemistry',
    slug: 'biochemistry',
    description: 'Metabolic pathways, molecular biology, clinical biochemistry, and genetics.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-path-04',
    college_id: 'col-gmc-01',
    name: 'Pathology',
    slug: 'pathology',
    description: 'General pathology, systemic pathology, hematology, and clinical pathology.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-phar-05',
    college_id: 'col-gmc-01',
    name: 'Pharmacology',
    slug: 'pharmacology',
    description: 'Autonomic, cardiovascular, antimicrobial therapeutics and clinical pharmacology.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-micr-06',
    college_id: 'col-gmc-01',
    name: 'Microbiology',
    slug: 'microbiology',
    description: 'Bacteriology, virology, mycology, parasitology, and immunology.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-med-07',
    college_id: 'col-gmc-01',
    name: 'General Medicine',
    slug: 'general-medicine',
    description: 'Internal medicine, cardiology, pulmonology, endocrinology, and critical care.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'sub-surg-08',
    college_id: 'col-gmc-01',
    name: 'General Surgery',
    slug: 'general-surgery',
    description: 'General surgical principles, trauma, gastrointestinal surgery, and urology.',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
];

export const INITIAL_EXAM_TYPES: ExamType[] = [
  {
    id: 'exam-ia-01',
    name: 'Internal Assessment',
    slug: 'internal-assessment',
    description: 'Periodic term evaluation conducted by department faculty.',
    is_active: true,
  },
  {
    id: 'exam-sem-02',
    name: 'Semester Examination',
    slug: 'semester-examination',
    description: 'End-of-semester comprehensive theory examination paper.',
    is_active: true,
  },
  {
    id: 'exam-univ-03',
    name: 'University Examination',
    slug: 'university-examination',
    description: 'Final university annual evaluation theory paper.',
    is_active: true,
  },
  {
    id: 'exam-prac-04',
    name: 'Practical Examination',
    slug: 'practical-examination',
    description: 'Spotting viva questions, OSPE, and clinical specimen question sheets.',
    is_active: true,
  },
  {
    id: 'exam-mod-05',
    name: 'Model Examination',
    slug: 'model-examination',
    description: 'Pre-university preparatory trial examination paper.',
    is_active: true,
  },
];

export const INITIAL_QUESTION_PAPERS: QuestionPaper[] = [
  {
    id: 'paper-001',
    college_id: 'col-gmc-01',
    subject_id: 'sub-anat-01',
    exam_type_id: 'exam-sem-02',
    mbbs_year: '1st MBBS',
    semester: 'Semester 1',
    exam_year: 2026,
    academic_year: '2025-2026',
    title: 'Anatomy Paper I — Upper Limb & Thorax',
    description: 'Includes long questions on Brachial Plexus injury, Coronary Circulation, and Histology spotting questions.',
    storage_path: 'mock/anatomy_2026_paper1.pdf',
    file_type: 'pdf',
    file_size: 980400,
    file_hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    original_file_name: 'Anatomy_1st_MBBS_Sem1_2026.pdf',
    page_count: 4,
    status: 'active',
    view_count: 142,
    download_count: 89,
    created_at: new Date('2026-02-15').toISOString(),
    updated_at: new Date('2026-02-15').toISOString(),
    published_at: new Date('2026-02-15').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Anatomy',
    exam_type_name: 'Semester Examination',
  },
  {
    id: 'paper-002',
    college_id: 'col-gmc-01',
    subject_id: 'sub-phys-02',
    exam_type_id: 'exam-univ-03',
    mbbs_year: '1st MBBS',
    semester: 'Annual',
    exam_year: 2025,
    academic_year: '2024-2025',
    title: 'Physiology University Theory Paper II',
    description: 'Renal physiology, neurophysiology, endocrine pathways, and special senses section.',
    storage_path: 'mock/physiology_2025_univ.pdf',
    file_type: 'pdf',
    file_size: 1120000,
    file_hash: '8f4e3c2b1a0987654321fedcba9876543210123456789abcdef0123456789abc',
    original_file_name: 'Physiology_Univ_2025_Final.pdf',
    page_count: 5,
    status: 'active',
    view_count: 210,
    download_count: 156,
    created_at: new Date('2025-11-10').toISOString(),
    updated_at: new Date('2025-11-10').toISOString(),
    published_at: new Date('2025-11-10').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Physiology',
    exam_type_name: 'University Examination',
  },
  {
    id: 'paper-003',
    college_id: 'col-gmc-01',
    subject_id: 'sub-bioc-03',
    exam_type_id: 'exam-ia-01',
    mbbs_year: '1st MBBS',
    semester: 'Semester 2',
    exam_year: 2025,
    academic_year: '2024-2025',
    title: 'Biochemistry 2nd Internal Assessment',
    description: 'Focus on Glycolysis, TCA Cycle, Lipid Metabolism disorders, and Liver Function Tests.',
    storage_path: 'mock/biochem_2025_ia2.pdf',
    file_type: 'pdf',
    file_size: 750000,
    file_hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    original_file_name: 'Biochem_IA2_2025.pdf',
    page_count: 3,
    status: 'active',
    view_count: 98,
    download_count: 62,
    created_at: new Date('2025-08-20').toISOString(),
    updated_at: new Date('2025-08-20').toISOString(),
    published_at: new Date('2025-08-20').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Biochemistry',
    exam_type_name: 'Internal Assessment',
  },
  {
    id: 'paper-004',
    college_id: 'col-gmc-01',
    subject_id: 'sub-path-04',
    exam_type_id: 'exam-sem-02',
    mbbs_year: '2nd MBBS',
    semester: 'Semester 3',
    exam_year: 2024,
    academic_year: '2023-2024',
    title: 'Pathology General & Hematology Paper',
    description: 'Neoplasia classification, Inflammation mechanisms, Anemia diagnostic charts, and Blood Banking.',
    storage_path: 'mock/pathology_2024_sem3.pdf',
    file_type: 'pdf',
    file_size: 1045000,
    file_hash: '7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d',
    original_file_name: 'Pathology_Sem3_2024.pdf',
    page_count: 4,
    status: 'active',
    view_count: 175,
    download_count: 112,
    created_at: new Date('2024-10-05').toISOString(),
    updated_at: new Date('2024-10-05').toISOString(),
    published_at: new Date('2024-10-05').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Pathology',
    exam_type_name: 'Semester Examination',
  },
  {
    id: 'paper-005',
    college_id: 'col-gmc-01',
    subject_id: 'sub-phar-05',
    exam_type_id: 'exam-univ-03',
    mbbs_year: '2nd MBBS',
    semester: 'Annual',
    exam_year: 2025,
    academic_year: '2024-2025',
    title: 'Pharmacology Annual University Paper I',
    description: 'Autonomic nervous system drugs, Cardiovascular drugs, and Antihypertensive therapy protocols.',
    storage_path: 'mock/pharmacology_2025_univ.pdf',
    file_type: 'pdf',
    file_size: 920000,
    file_hash: '9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    original_file_name: 'Pharm_Univ_Paper1_2025.pdf',
    page_count: 4,
    status: 'active',
    view_count: 188,
    download_count: 140,
    created_at: new Date('2025-06-18').toISOString(),
    updated_at: new Date('2025-06-18').toISOString(),
    published_at: new Date('2025-06-18').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Pharmacology',
    exam_type_name: 'University Examination',
  },
  {
    id: 'paper-006',
    college_id: 'col-gmc-01',
    subject_id: 'sub-micr-06',
    exam_type_id: 'exam-prac-04',
    mbbs_year: '2nd MBBS',
    semester: 'Semester 4',
    exam_year: 2024,
    academic_year: '2023-2024',
    title: 'Microbiology Practical Spotting & Viva Guide',
    description: 'Culture media identification, Gram stain slide viva questions, and Parasitology specimens.',
    storage_path: 'mock/microbiology_2024_prac.pdf',
    file_type: 'pdf',
    file_size: 890000,
    file_hash: '3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b',
    original_file_name: 'Micro_Practical_2024.pdf',
    page_count: 6,
    status: 'active',
    view_count: 130,
    download_count: 95,
    created_at: new Date('2024-04-12').toISOString(),
    updated_at: new Date('2024-04-12').toISOString(),
    published_at: new Date('2024-04-12').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Microbiology',
    exam_type_name: 'Practical Examination',
  },
  {
    id: 'paper-007',
    college_id: 'col-gmc-01',
    subject_id: 'sub-med-07',
    exam_type_id: 'exam-mod-05',
    mbbs_year: 'Final MBBS',
    semester: 'Semester 9',
    exam_year: 2026,
    academic_year: '2025-2026',
    title: 'General Medicine Model Theory Examination Paper I',
    description: 'Cardiovascular emergencies, Myocardial Infarction management, Stroke protocols, and Acute Kidney Injury.',
    storage_path: 'mock/medicine_2026_model.pdf',
    file_type: 'pdf',
    file_size: 1350000,
    file_hash: '5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    original_file_name: 'Medicine_Model_Paper1_2026.pdf',
    page_count: 5,
    status: 'active',
    view_count: 260,
    download_count: 198,
    created_at: new Date('2026-01-20').toISOString(),
    updated_at: new Date('2026-01-20').toISOString(),
    published_at: new Date('2026-01-20').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'General Medicine',
    exam_type_name: 'Model Examination',
  },
  {
    id: 'paper-008',
    college_id: 'col-gmc-01',
    subject_id: 'sub-surg-08',
    exam_type_id: 'exam-univ-03',
    mbbs_year: 'Final MBBS',
    semester: 'Annual',
    exam_year: 2025,
    academic_year: '2024-2025',
    title: 'General Surgery University Examination Paper II',
    description: 'Acute abdomen management, Appendicitis vs Diverticulitis, Thyroid carcinoma, and Breast cancer staging.',
    storage_path: 'mock/surgery_2025_univ.pdf',
    file_type: 'pdf',
    file_size: 1280000,
    file_hash: '1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f',
    original_file_name: 'Surgery_Paper2_Univ_2025.pdf',
    page_count: 5,
    status: 'active',
    view_count: 310,
    download_count: 245,
    created_at: new Date('2025-05-14').toISOString(),
    updated_at: new Date('2025-05-14').toISOString(),
    published_at: new Date('2025-05-14').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'General Surgery',
    exam_type_name: 'University Examination',
  },
  {
    id: 'paper-009',
    college_id: 'col-gmc-01',
    subject_id: 'sub-anat-01',
    exam_type_id: 'exam-univ-03',
    mbbs_year: '1st MBBS',
    semester: 'Annual',
    exam_year: 2023,
    academic_year: '2022-2023',
    title: 'Anatomy University Paper II — Abdomen, Pelvis & Neuroanatomy',
    description: 'Peritoneal reflections, Portal circulation, Cerebral cortex functional areas, and Spinal cord tracts.',
    storage_path: 'mock/anatomy_2023_univ.pdf',
    file_type: 'pdf',
    file_size: 1020000,
    file_hash: 'b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2',
    original_file_name: 'Anatomy_Univ_Paper2_2023.pdf',
    page_count: 4,
    status: 'active',
    view_count: 165,
    download_count: 110,
    created_at: new Date('2023-11-20').toISOString(),
    updated_at: new Date('2023-11-20').toISOString(),
    published_at: new Date('2023-11-20').toISOString(),
    college_name: 'Government Medical College (GMC)',
    subject_name: 'Anatomy',
    exam_type_name: 'University Examination',
  },
];

export const INITIAL_REPORTS: PaperReport[] = [
  {
    id: 'rep-001',
    paper_id: 'paper-006',
    reason: 'incomplete',
    description: 'Page 3 of the practical spotting guide is cut off near the bottom margin.',
    status: 'pending',
    created_at: new Date('2026-02-28').toISOString(),
    paper_title: 'Microbiology Practical Spotting & Viva Guide',
    subject_name: 'Microbiology',
  },
];
